
platform :ios, '8.0'

use_frameworks!

def pods
    pod 'RxSwift', '3.6.1'
    pod 'RxCocoa', '3.6.1'
    pod 'Kingfisher', '3.10.2'
    pod 'RxDataSources', '1.0.4'
    pod 'ReactorKit'
end


target ‘RxBasicInterface’ do
    pods
end
